// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp0EIYD2tCmcZENUOBFaU_BgHM9R7nwyA',
    appId: '1:727814898479:web:28026380e63900de9d57da',
    messagingSenderId: '727814898479',
    projectId: 'mixify-cd066',
    authDomain: 'mixify-cd066.firebaseapp.com',
    storageBucket: 'mixify-cd066.appspot.com',
    measurementId: 'G-KXR37FBVT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtCRcks9wL4-NTAaznYFdlxAI-5mCtLbc',
    appId: '1:727814898479:android:858b096249aa950d9d57da',
    messagingSenderId: '727814898479',
    projectId: 'mixify-cd066',
    storageBucket: 'mixify-cd066.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXqUMr_yqTfDarHPWkKM63f4j2Q6sZ5RA',
    appId: '1:727814898479:ios:f34b51953c44d47e9d57da',
    messagingSenderId: '727814898479',
    projectId: 'mixify-cd066',
    storageBucket: 'mixify-cd066.appspot.com',
    iosBundleId: 'com.keller.code',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXqUMr_yqTfDarHPWkKM63f4j2Q6sZ5RA',
    appId: '1:727814898479:ios:5185041c94bdc52b9d57da',
    messagingSenderId: '727814898479',
    projectId: 'mixify-cd066',
    storageBucket: 'mixify-cd066.appspot.com',
    iosBundleId: 'com.keller.code.RunnerTests',
  );
}
